kind: Service
apiVersion: v1
metadata:
  name: playground-service
spec:
  type: ClusterIP
  selector:
    app: iot-playground
  ports:
    - name: http
      port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-deploy
  labels:
    app: iot-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-playground
  template:
    metadata:
      labels:
        app: iot-playground
    spec:
      containers:
      - name: playground-app
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
