SERVER_NAME = "jereligiS"
SERVER_IP = "192.168.56.110"

BOX = "debian/bullseye64"
CPU = 1
MEMORY = 2048

Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.vm.box_check_update = false
  
  config.vm.define SERVER_NAME do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network "private_network", ip: SERVER_IP

    server.vm.provider "virtualbox" do |vb|
      vb.name = SERVER_NAME
      vb.cpus = CPU
      vb.memory = MEMORY
    end

    server.vm.provision "file", source: "./confs", destination: "./confs"
    server.vm.provision "shell", inline: <<-SHELL
      apt-get update -y ;
      apt-get install -y curl ;
      curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="" sh - ;
    SHELL
  end
end
