Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  # config.vm.box_check_update = false
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.56.110"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "jereligi"
    vb.cpus = 1
    vb.memory = 1024
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_ENABLE=true sh -
  SHELL
end
