SERVER_NAME = "jereligiS"
SERVER_IP = "192.168.56.110"

WORKER_NAME = "jereligiSW"
WORKER_IP = "192.168.56.111"

BOX = "debian/bullseye64"

Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 1024
  end
  
  config.vm.define SERVER_NAME do |server|
    server.vm.box = BOX
    server.vm.box_check_update = false
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.hostname = SERVER_NAME

  config.vm.provision "shell", inline: <<-SHELL
    apt update -y ;
    apt install -y curl ;
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san $SERVER_IP --node-external-ip $SERVER_IP --flannel-iface=eth1" sh -;
    # sudo chmod 644 /etc/rancher/k3s/k3s.yaml
    # sudo cp "/var/lib/rancher/k3s/server/node-token" "/vagrant"
  SHELL
  end

  config.vm.define WORKER_NAME do |worker|
    worker.vm.box = BOX
    worker.vm.box_check_update = false
    worker.vm.network "private_network", ip: WORKER_IP
    worker.vm.hostname = WORKER_NAME

  # config.vm.provision "file", source: "./node-token", destination: "./"
  config.vm.provision "shell", inline: <<-SHELL
    apt update -y ;
    apt install -y curl ;
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-iface=eth1" K3S_TOKEN=mycustomtoken K3S_URL=https://192.168.58.110:6443 sh -
  SHELL
  end

end
